qonto/ember-amount-input

addon/styles/ember-amount-input.css
[//]: # "Please include a summary of the change and which issue is fixed. Imagine you're trying to explain the changes to a reviewer."
Firefox applies an opacity on input placeholder, which creates a difference between the currency and placeholder.
Also, `ember-cli-addon-docs` adds opacity too.
See:
**Changes**
* Force opacity on placeholder
[//]: # "Please delete options that are not relevant, or add what is."
* Bug fix
[//]: # "Please add screenshots if you made any UI changes."
[//]: # "Please add instructions to reproduce the changes."
Check the input in the demo: https://qonto.github.io/ember-amount-input/versions/master/docs/components/amount-input
[//]: # "Please delete options that are not relevant, or add what is."
* Style
=> 🐛💄 Force placeholder opacity

.travis.yml, package.json
This PR aims to drop `node 8` support as it has reaches is end of life
see https://nodejs.org/en/about/releases/
* Update `package.json` to udpdate engines
* Update `.travis-ci.yml`
=> 💥 Drop node 8 support 

.dependabot/config.yml
This aims to add the .depandabot/config.yml file in the repo to in order to have a local configuratoin instead of inheriting from the organization settings.
Add .dependabot/config.yml
=> 🔧 add Dependabot config file

addon/components/amount-input/template.hbs
[//]: # Adds an `id` attribute to the `<input>` in the template. This will allow users to include an associated `<label for="">` to improve accessibility.
* Adds an `id` of `amount-input` to the `<input>` in the template. 
[//]: # This is a very simple change that does not alter the behavior of the addon.
=> :wheelchair: add id attribute to input

addon/components/amount-input/component.js, tests/integration/components/amount-input/component-test.js
- Disallows 'e' key on input
- Disallows '.' keypress when numberOfDecimals is 0
- Disallows ',' keypress for french keyboard when numberOfDecimals is 0 
Also fixes https://github.com/qonto/ember-amount-input/issues/149
=> inputmask . when numberOfDecimals=0 and always mask e key

.travis.yml, config/ember-try.js
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."
This will be released as breaking change in a v3. 
If you use a version of ember-source lower than 3.16, ember-amount-input v3 might work but it is not guaranteed. If it is not, you can use ember-amount-input v2.
The CI was failing on the following error with `ember-source@<3.10`.
```
Uncaught Error: Assertion Failed: computed expects a function or an object as last argument.
```
=> Update ember-try config to drop compatibility with ember versions lower than 3.16

.travis.yml, package.json
This PR drops support for NodeJs 10 and 13. These versions are eol ([NodeJs versions schedule](https://nodejs.org/en/about/releases/)).
It should be released in major version.
=> Drop NodeJs 10 and 13 support

testem.js
It takes the latest config from [ember-cli blueprints](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/testem.js).
=> Increase browser timeout in testem config

package.json, yarn.lock
While the CI was passing for the PR, it fails on the main branch. This PR proposes to revert [Dependabot's ember-cli-babel upgrade](https://github.com/qonto/ember-amount-input/pull/275/checks).
=> Revert Dependabot's ember-cli-babel upgrade

addon/components/amount-input.hbs, addon/components/amount-input.js, tests/integration/components/amount-input/component-test.js
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."
Currently the input id defaults to `amount-input`. If you have more than one `<AmountInput/>` in a document their ids are no longer unique, element ids should be unique. This PR keeps the default `amount-input` id but let you override it using `@inputId` argument.
* Add named argument `@inputId` to allow setting the input id
This last checklist item doesn't appear relevant anymore
~- [ ] Add a playground example in tests/dummy/app/pods/docs/components/amount-input/all-options/template~
=> Add named argument `@inputId` to allow setting the input id

addon/components/amount-input.hbs, addon/components/amount-input.js, tests/dummy/app/templates/docs/components/amount-input.md, tests/integration/components/amount-input/component-test.js
[//]: # Added readonly attribute (resolve #307)
* Added readonly attribute to the component
* Added test ad updated docs
=> Added readonly attribute

addon/components/amount-input.js
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."
This MR makes use of the [valueAsNumber](https://www.w3.org/TR/2011/WD-html5-20110405/common-input-element-attributes.html#dom-input-valueasnumber) property of input, instead of parsing manually the value as a float.
[caniuse table](https://caniuse.com/mdn-api_htmlinputelement_valueasnumber)
* use `e.currentTarget.valueAsNumber` instead of `e.currentTarget.value` in the onFocusOut handler
* Remove the parseFloat call as this already returns a float.
=> use already parsed e.target.valueAsNumber value instead of e.target.value

addon/components/amount-input.js, tests/integration/components/amount-input/component-test.js
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."
This MR fixes an issue I introduced in https://github.com/qonto/ember-amount-input/pull/410 where falsy numbers (0; 0.00 etc) would not trigger the extra `update` call with a formatted value. 🙇🏾 
* Add failing test `should call update with the formatted value on blur if the value is 0`
* Fix the condition used to call this.args.update in the onFocusOut handler.
=> fix issue where 0 would not trigger an update call on blur

addon/components/amount-input.hbs, addon/components/amount-input.js, tests/dummy/app/templates/docs/components/amount-input.md, tests/integration/components/amount-input/component-test.js
This MR is to address the issue #151 [Expose min and max attributes on the input element](https://github.com/qonto/ember-amount-input/issues/151)
No UI Changes
=> Expose min and max attributes

.github/workflows/ci.yml, .github/workflows/release.yml
This MR removes the double `pnpm install`: `NullVoxPopuli/action-setup-pnpm` already calls `pnpm install` and expose an `args` input
=> ci: remove double pnpm install on CI

.github/workflows/ci.yml, .github/workflows/release.yml, package.json
This MR use the packageManager as the source of truth for pnpm version in CI. 
This remove duplication (and potential errors) in the ci files.
The [setup-pnpm action](https://github.com/NullVoxPopuli/action-setup-pnpm#support) and [dependabot](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/package_manager.rb) already support this.
=> ci: use packageManager to set pnpm version

ember-amount-input/src/components/amount-input.js
Hello! I noticed a behaviour that looks a bit weird to me and led to a bug ticket in Production ([here](https://www.notion.so/qonto/Cannot-input-0-as-last-cents-digit-in-Instant-card-creation-flow-budget-for-the-card-5bedadb8c2704010957f133be29b590b) for Qonto employees).
When `@numberOfDecimal` is set to `0` (so `@value` should always be an integer), following filtering logic is used for `e`, `,`, and `.` key presses:
```javascript
// ember-amount-input/src/components/amount-input.js
@action
onKeyDown(event) {
if (event.keyCode === KEY_CODE_E) {
return false;
} else if (
this.numberOfDecimal === 0 &&
[KEY_CODE_FULLSTOP, KEY_CODE_COMMA].includes(event.keyCode)
) {
return false;
}
}
```
But, since the events are not prevented from bubbling, you can actually type those characters in the …
=> Bug fix: Prevent event propagation on invalid key presses

.github/workflows/ci.yml
We want to use `wyvox/action-setup-pnpm@v3` (instead of `NullVoxPopuli/action-setup-pnpm@v2`) in our CI script.
Indeed, `NullVoxPopuli/action-setup-pnpm` has been [archived](https://github.com/NullVoxPopuli/action-setup-pnpm) and moved to [another repository](https://github.com/wyvox/action-setup-pnpm).
We also stop using the `no-lockfile` boolean option, as it has been dropped in the [last release](https://github.com/wyvox/action-setup-pnpm/releases/tag/v3.0.0), and it's now recommended to pass the pnpm option `--no-lockfile` directly via the args.
=> Update action to setup pnpm

.github/workflows/release.yml
This PR is a follow-up of [this one](https://github.com/qonto/ember-amount-input/pull/546), where we migrated from `NullVoxPopuli/action-setup-pnpm@v2` to `wyvox/action-setup-pnpm@v3` in the CI jobs script. Here we take care of the release script.
=> Update action to setup pnpm in release script

.github/dependabot.yml
We update the interval of the `dependabot.yml` config from weekly to daily, in order to quickly recreate old dependencies PRs.
=> chore(deps): update dependabot config interval from weekly to daily

pnpm-lock.yaml, test-app/package.json
We manually update webpack requirement from ^5.81.0 to ^5.88.1 in `/test-app` because the previous dependabot PR was created with an old `dependabot.yml`.
=> chore(deps): update webpack requirement from ^5.81.0 to ^5.88.1 in /test-app 

ember-amount-input/package.json, pnpm-lock.yaml, test-app/package.json
In this PR, we bump all Babel-related dependencies to the latest versions in `ember-amount-input` and `test-app` packages.
=> chore(dev-deps): bump Babel related dependencies

.github/dependabot.yml
After this first [PR](https://github.com/qonto/ember-amount-input/pull/550), we update the interval of the dependabot.yml config back to a weekly interval.
=> chore: update dependabot config interval from daily to weekly

README.md
We are not using Travis-CI anymore for this project. We can’t use the build status badge on the README anymore. So we propose to replace it with a badge displaying the status of the GitHub CI workflow (master branch). You can have a preview of the updated README via this [link](https://github.com/qonto/ember-amount-input/tree/update-build-badge).
=> chore: replace Travis-CI build status badge with GitHub CI workflow badge

ember-amount-input/package.json, pnpm-lock.yaml
We currently declare `ember-source@4.0.0`  as a peer dependency. But we shouldn't. Indeed, we still have test scenarios for ember-lts-3.28  and ember-classic, working perfectly fine. Plus, we still indicate the compatibility of Ember.js v3.28 (and above) in the README. There are 2 options: remove this declaration, or improve it with an explicit range. We are going with the second option.
=> fix(peer-deps): explicitly set ember-source versions range

ember-amount-input/package.json, pnpm-lock.yaml, test-app/config/ember-try.js
We want to bump `@embroider/addon-dev` from 3.0.0 to 4.1.0.
However, Ember-try's default configuration with pnpm installs lower versions of embroider devDependencies when running ember-try scenarios. So we need to bump embroider dependencies in ember-try config to make sure newer versions are installed in order to fix embroider ember-try CI jobs failing.
It should resolve https://github.com/qonto/ember-amount-input/pull/568.
See https://github.com/qonto/ember-phone-input/pull/732 and https://github.com/qonto/ember-autofocus-modifier/pull/409 for references.
=> chore(deps): bump embroider versions in ember-try config

.github/workflows/ci.yml, test-app/config/ember-try.js
In a [previous PR](https://github.com/qonto/ember-amount-input/pull/552), we bumped `ember-source` to v5 in test-app. So we want to add new test scenarios to the CI, for LTS versions (v.4.8.0 and v4.12.0).
Give a look at the [checks of this PR](https://github.com/qonto/ember-amount-input/actions/runs/6341923874) to see the new two new ones.
See [Ember LTS versions](https://emberjs.com/releases/lts/).
=> ci: add LTS ember-try scenarios for v4.8.0 and v4.12.0

ember-amount-input/.eslintrc.cjs, test-app/.eslintrc.js
In this PR, we update the rules in our TS eslint config to allow the use of the `private` and `protected` keywords in TypeScript classes definition.
=> feat(ts-lint): allow use of private and protected syntax for classes in .ts files

ember-amount-input/.eslintrc.cjs, ember-amount-input/package.json, pnpm-lock.yaml, test-app/.eslintrc.js, test-app/package.json
Install and use our custom ESLint configuration found on https://github.com/qonto/eslint-config-typescript
The currently available version is a RC (Release Candidate) that we're testing on our public repos before making it stable.
=> chore: install and use @qonto/eslint-config-typescript@1.0.0-rc.0

DOCS.md
In this PR, we add a section dedicated to TypeScript in DOCS.md. See [ember-lottie](https://github.com/qonto/ember-lottie#typescript-usage) for reference.
=> docs: add TypeScript usage section

.release-it.js, RELEASE.md, package.json, pnpm-lock.yaml
In this PR, we replace @release-it-plugins/lerna-changelog with @release-it/conventional-changelog in order to leverage Conventional Commit messages and update the CHANGELOG seamlessly.
This makes the entire process even more straightforward, as no preparation work is required ahead of a new release.
=> Set up Conventional Changelog plugin for release-it 

CHANGELOG.md
This MR fixes a release issue where CHANGELOG didn't get updated properly with th v7 release.
=> fix: replace v7-beta0 with v7 in changelog

.github/workflows/commitlint.yml, .github/workflows/release.yml
This MR fixes a typo where we use main instead of master branch in CI workflows
=> chore(ci): use master branch instead of main in CI scripts

ember-amount-input/src/components/amount-input.hbs, ember-amount-input/src/components/amount-input.ts, test-app/tests/integration/components/amount-input/component-test.ts, test-app/tests/integration/components/amount-input/helpers/paste-value.ts
This MR aims at fixing this issue described here : https://github.com/qonto/ember-amount-input/issues/773
by providing better support for paste from clipboard: 
- it listen to the paste event
- tries to parse values omitting the spaces
=> Improve pasting from clipboard values support

ember-amount-input/src/components/amount-input.ts
This MR goal is to get rid of the usage of `KeyboardEvent.keyCode` which is a deprecated standard as you can see on [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). As of today, this is still supported by all browsers but might no be the case in the future. 
Two API have the potential to replace `keyCode` and they're `KeyboardEvent.code` and `KeyboardEvent.key`.
`KeyboardEvent.code` returns a representation of the key pressed while `KeyboardEvent.key` returns the value as it will be printed. In our case, we want to exclude specific printed values so `key` usage makes more sense.
Also, `KeyboardEvent.key` is more supported by browsers (partial support up to IE 8 for instance).
This PR closes #612 issue. 
Tests should pass.
=> feat: use KeyboardEvent.key instead of KeyboardEvent.keyCode

ember-amount-input/src/components/amount-input.ts, test-app/tests/integration/components/amount-input/component-test.ts
In this MR, we want to prevent the default behavior of the paste event.
Indeed, the default behavior of the paste event includes triggering the input event right after. However, the component calls the `update` function for both events, which can lead to unexpected results.
By preventing the default behavior of the paste event, we make sure the `update` function is only called once.
=> Fix: prevent default behavior for the paste event
